"""Deterministic rendering of a :class:`TestPlan` into pytest source.

The LLM's output stays confined to the plan schema; everything that becomes
code on disk goes through these templates, so re-planning produces meaningful
diffs and house style is enforced here, not by the model.
"""

from __future__ import annotations

import keyword
import re

from .schema import TestCase, TestPlan

GENERATED_HEADER = """\
# Generated by pyllym.tdg from feature: {feature}
# These tests are the specification. Do not edit them during implementation;
# regenerate from the .toml spec instead.
"""


def _identifier(name: str, *, prefix: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]+", "_", name.strip()).strip("_").lower()
    if not ident.startswith(prefix):
        ident = f"{prefix}{ident}" if ident else f"{prefix}case"
    if not ident.isidentifier() or keyword.iskeyword(ident):
        ident = f"{prefix}case"
    return ident


def _unique(name: str, taken: set[str]) -> str:
    candidate, n = name, 2
    while candidate in taken:
        candidate = f"{name}_{n}"
        n += 1
    taken.add(candidate)
    return candidate


def _body_lines(case: TestCase) -> list[str]:
    lines: list[str] = []
    if case.covers:
        lines.append(f"# Covers: {', '.join(case.covers)}")
    if case.notes:
        lines.append(f"# {case.notes}")
    if case.given:
        lines.append(f"# Given: {case.scenario}")
        lines.extend(case.given)
    lines.append("# When")
    # An act that is itself a statement (canonical error-path form puts the
    # act in `given` and sets when to "None") renders without the assignment.
    lines.append(case.when if case.when.strip() == "None" else f"result = {case.when}")
    if case.then:
        lines.append("# Then")
        lines.extend(f"assert {expr}" for expr in case.then)
    return lines


def render_tests(plan: TestPlan) -> str:
    """Render a complete, syntactically valid, red pytest module."""
    out: list[str] = ["from __future__ import annotations", ""]
    out.append(GENERATED_HEADER.format(feature=plan.feature))
    out.append("import pytest")
    for imp in plan.api.imports:
        out.append(imp)
    out.append("")
    out.append("pytestmark = [pytest.mark.bdd_pending]")

    taken: set[str] = set()
    for fixture in plan.fixtures:
        name = _unique(_identifier(fixture.name, prefix=""), taken)
        out.append("")
        out.append("")
        out.append("@pytest.fixture")
        out.append(f"def {name}():")
        body = fixture.body or ["return None"]
        out.extend(f"    {line}" for line in body)

    for case in plan.cases:
        name = _unique(_identifier(case.test_name, prefix="test_"), taken)
        params = ", ".join(case.fixtures)
        out.append("")
        out.append("")
        if case.edge_case:
            out.append(f"# Edge case derived from: {case.scenario}")
        if case.is_async:
            out.append("@pytest.mark.asyncio")
            out.append(f"async def {name}({params}):")
        else:
            out.append(f"def {name}({params}):")
        out.extend(f"    {line}" for line in _body_lines(case))

    return "\n".join(out) + "\n"


def render_conftest() -> str:
    """A conftest for the output directory registering the marker."""
    return (
        "from __future__ import annotations\n"
        "\n"
        "\n"
        "def pytest_configure(config):\n"
        "    config.addinivalue_line(\n"
        '        "markers", "bdd_pending: generated from a BDD feature; red until implemented"\n'
        "    )\n"
    )
